# Generated by Django 5.2.13 on 2026-05-04 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('make', models.CharField(choices=[('toyota', 'Toyota'), ('bmw', 'BMW'), ('mercedes', 'Mercedes-Benz'), ('audi', 'Audi'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('chevrolet', 'Chevrolet'), ('lexus', 'Lexus'), ('nissan', 'Nissan'), ('honda', 'Honda'), ('mazda', 'Mazda'), ('mitsubishi', 'Mitsubishi'), ('subaru', 'Subaru'), ('volkswagen', 'Volkswagen'), ('ford', 'Ford'), ('porsche', 'Porsche'), ('land_rover', 'Land Rover'), ('genesis', 'Genesis'), ('haval', 'Haval'), ('other', 'Другое')], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('generation', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник / SUV'), ('crossover', 'Кроссовер')], max_length=30)),
                ('transmission', models.CharField(choices=[('automatic', 'Автомат'), ('manual', 'Механика'), ('robot', 'Робот'), ('variator', 'Вариатор')], max_length=20)),
                ('fuel', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas_petrol', 'Газ/Бензин'), ('hybrid', 'Гибрид')], max_length=20)),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=4)),
                ('drive', models.CharField(choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный (AWD/4WD)')], max_length=10)),
                ('steering', models.CharField(choices=[('left', 'Левый руль'), ('right', 'Правый руль')], default='left', max_length=10)),
                ('color', models.CharField(blank=True, choices=[('white', 'Белый'), ('black', 'Черный'), ('silver', 'Серебристый'), ('red', 'Красный'), ('other', 'Другой')], max_length=20)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('owners_count', models.IntegerField(default=1)),
                ('condition', models.CharField(choices=[('used', 'Б/У'), ('new', 'Новый'), ('damaged', 'Аварийный')], default='used', max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('currency', models.CharField(choices=[('usd', 'USD ($)'), ('kgs', 'Сом (с)')], default='usd', max_length=5)),
                ('price_kgs', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('has_installment', models.BooleanField(default=False)),
                ('region', models.CharField(choices=[('bishkek', 'Бишкек'), ('osh', 'Ош'), ('chuy', 'Чуй областы'), ('issyk_kul', 'Ысык-Куль областы'), ('jalal_abad', 'Жалал-Абад областы'), ('batken', 'Баткен областы'), ('naryn', 'Нарын областы'), ('talas', 'Талас областы'), ('osh_region', 'Ош областы')], max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('has_photo', models.BooleanField(default=True)),
                ('is_customs_cleared', models.BooleanField(default=False)),
                ('has_gas_equipment', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_exchange_possible', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('sold', 'Продано'), ('hidden', 'Скрыто')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/photos/%Y/%m/')),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.carlisting')),
            ],
            options={
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('region', models.CharField(blank=True, choices=[('bishkek', 'Бишкек'), ('osh', 'Ош'), ('chuy', 'Чуй областы'), ('issyk_kul', 'Ысык-Куль областы'), ('jalal_abad', 'Жалал-Абад областы'), ('batken', 'Баткен областы'), ('naryn', 'Нарын областы'), ('talas', 'Талас областы'), ('osh_region', 'Ош областы')], max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cars.carlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
