# Generated by Django 5.2.13 on 2026-05-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник / SUV'), ('hatchback', 'Хэтчбек'), ('wagon', 'Универсал'), ('coupe', 'Купе'), ('convertible', 'Кабриолет'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('crossover', 'Кроссовер'), ('truck', 'Грузовик'), ('van', 'Фургон'), ('other', 'Другой')], max_length=30),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='fuel',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ (LPG)'), ('hybrid', 'Гибрид'), ('electric', 'Электро'), ('gas_petrol', 'Газ/Бензин')], max_length=20),
        ),
    ]
